In [9]:
import tensorflow as tf
import numpy as np

### Softmax 

Part of the function worth mentioning ( in building machine learning model ) is the softmax function. Its corresponding implementation in tensorflow is tf.nn.softmax

<p><b> tf.nn.softmax( ) </b>:</p>
<p>This produces  the result of applying the softmax function to an input tensor.</p>

 $$\sigma(z)_j = \frac{e^{z_j}} {\Sigma_{k=1}^K e^{z_k} }  $$  
 $$ for \quad  j  =  1, …, K $$



</p>

<p> The softmax "squishes" the inputs so that sum ( input ) = 1; it's a way of normalizing. The shape of output of a softmax is the same as the input - it just normalizes the values. The outputs of softmax can be interpreted as probabilities. </p>

Source: http://stackoverflow.com/questions/34240703/difference-between-tensorflow-tf-nn-softmax-and-tf-nn-softmax-cross-entropy-with


In [2]:
with tf.Session() as sess:    
    a = tf.constant(np.array([[.1, .3, .5, .9]]))
    print sess.run(tf.nn.softmax(a))


[[ 0.16838508  0.205666    0.25120102  0.37474789]]


### tf.nn.softmax_cross_entropy_with_logits
Computes softmax cross entropy between logits and labels. Use this in a classification problem

<p>It computes the cross entropy of the result after applying the softmax function (but it does it all together in a more mathematically careful way). It's similar to the result of:

sm = tf.nn.softmax(x)
ce = cross_entropy(sm)

In [ ]:
#Use this in classification problem 
# y is prediction
# label_nodes is target. 
# This becomes the cost function
---cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y, label_nodes))

<p>The cross entropy is a summary metric - it sums across the elements. The output of tf.nn.softmax_cross_entropy_with_logits on a shape [2,5] tensor is of shape [2,1] (the first dimension is treated as the batch).</p>

### tf.reduce_mean( )


<p>The arithmetic mean is the sum of the elements along the axis divided by the number of elements. </p>

In [12]:
#Using Numpy without specifying axis
array = np.array([[1, 2], [3, 4]])
np.mean(array)


2.5

In [14]:
#specify the axis
np.mean(array, axis=0)

array([ 2.,  3.])

In [24]:
# The results is same as for Tensor flow
array_mean = np.array([[3.,5], [5,0], [9.,12]])
print(array_mean)
print("the result from numpy mean operation: ", np.mean(array_mean,1))

Mean = tf.reduce_mean(c,1)
with tf.Session() as sess:
    result = sess.run(Mean)
    print("result from tf.mean: ", result)

[[  3.   5.]
 [  5.   0.]
 [  9.  12.]]
('the result from numpy mean operation: ', array([  4. ,   2.5,  10.5]))
('result from tf.mean: ', array([ 3.5,  5.5,  6.5]))


### tf.truncated_normal

Outputs random values from a truncated normal distribution.

In [33]:
# We show how to initialise variable by a constant
# And initialising using tf.constant

y_constant = tf.constant(0.1, shape=[4]); #initialise a constant
r_var = tf.Variable(y)   # initialise constant by variabel.
# Both ways above can be used to initialise the bias variables                       
weight = tf.Variable(tf.truncated_normal([4, 5])) # weight initialisation with tf.truncated_normal

init_op = tf.global_variables_initializer() # initialise varianle

with tf.Session() as sess:
    sess.run(init_op)
    print("y_constant and r_var are same values:")
    print(y_constant.eval());

    print(r_var.eval());print("\n");
    print("weight initialised with truncated normal: ")

    print(weight.eval())

y_constant and r_var are same values:
[ 0.1  0.1  0.1  0.1]
[ 0.1  0.1  0.1  0.1]


weight initialised with truncated normal: 
[[ 0.95871228  0.28760111 -0.08963373  1.41321909  1.88666642]
 [-0.45240343 -0.42291233 -0.90050316  0.78051525 -0.66701406]
 [-1.77560961 -0.91545683  0.74849337 -1.31004107 -0.25731021]
 [-1.00727427 -0.69677335 -1.1047287   1.66000664  0.12934102]]
